version: '3'
services:
  redis-server:
    build:
      context: ./
      dockerfile: redis.docker
    container_name: redis 
  node-app:
    #restart: always
    build: .
    ports:
      - "4001:8081"
